name: Build Godot export templates

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    env:
      GODOT_VERSION: 4.6.1-stable

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: android
            arch: arm64
            type: release
            runner: ubuntu-24.04

          - target: android
            arch: arm64
            type: debug
            runner: ubuntu-24.04

          - target: android
            arch: arm32
            type: release
            runner: ubuntu-24.04

          - target: android
            arch: arm32
            type: debug
            runner: ubuntu-24.04

          # Linux
          - target: linuxbsd
            arch: x86_64
            type: release
            runner: ubuntu-22.04

          - target: linuxbsd
            arch: x86_64
            type: debug
            runner: ubuntu-22.04

          # - target: linuxbsd
          #   arch: arm64
          #   runner: ubuntu-22.04

          - target: linuxbsd
            arch: x86_32
            type: release
            runner: ubuntu-22.04

          - target: linuxbsd
            arch: x86_32
            type: debug
            runner: ubuntu-22.04

          # Windows
          - target: windows
            arch: x86_64
            type: release
            runner: ubuntu-24.04

          - target: windows
            arch: x86_64
            type: debug
            runner: ubuntu-24.04

          # - target: windows
          #   arch: arm64
          #   runner: ubuntu-24.04

          - target: windows
            arch: x86_32
            type: release
            runner: ubuntu-24.04

          - target: windows
            arch: x86_32
            type: debug
            runner: ubuntu-24.04

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.2"

      - name: Build platform ${{ matrix.target }}-${{ matrix.arch }}
        run: curl -fsSL https://raw.githubusercontent.com/nndda/build-godot/b2be9a15d1fdc5230efddcf759abdf40b15cb634/build-exports.sh | bash
        env:
          EXPORT_PLATFORM: ${{ matrix.target }}
          EXPORT_ARCH: ${{ matrix.arch }}
          EXPORT_TYPE: ${{ matrix.type }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: export-template-${{ matrix.target }}-${{ matrix.arch }}
          path: ${{ matrix.target }}-${{ matrix.arch }}.7z
