name: Uwu

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      GODOT_VERSION: 4.6-stable

    strategy:
      matrix:
        target:
          # - linux
          - windows

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.2"

      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            scons \
            pkg-config \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libasound2-dev \
            libpulse-dev \
            libudev-dev \
            libxi-dev \
            libxrandr-dev \
            libwayland-dev \
            mingw-w64 \
            unzip \
            curl

          echo "Python version:"
          python --version

          echo "MinGW-w64 version:"
          x86_64-w64-mingw32-gcc --version
          i686-w64-mingw32-gcc --version

      - name: Checkout Godot source code repository
        uses: actions/checkout@v6
        with:
          repository: godotengine/godot
          ref: ${{ env.GODOT_VERSION }}

      - name: Set build options
        run: |
          cat <<EOF > custom.py
          production = "yes"
          disable_3d = "yes"
          minizip = "no"
          deprecated = "no"
          module_basis_universal_enabled = "no"
          module_bmp_enabled = "no"
          module_camera_enabled = "no"
          module_csg_enabled = "no"
          module_dds_enabled = "no"
          module_enet_enabled = "no"
          module_gltf_enabled = "no"
          module_gridmap_enabled = "no"
          module_hdr_enabled = "no"
          module_jpg_enabled = "no"
          module_jsonrpc_enabled = "no"
          module_ktx_enabled = "no"
          module_meshoptimizer_enabled = "no"
          module_minimp3_enabled = "no"
          module_mobile_vr_enabled = "no"
          module_msdfgen_enabled = "no"
          module_navigation_enabled = "no"
          module_openxr_enabled = "no"
          module_raycast_enabled = "no"
          module_tga_enabled = "no"
          module_theora_enabled = "no"
          module_upnp_enabled = "no"
          module_vhacd_enabled = "no"
          module_webrtc_enabled = "no"
          module_websocket_enabled = "no"
          module_webxr_enabled = "no"
          module_zip_enabled = "no"
          openxr = "no"
          EOF

      - name: Build Linux export templates
        if: ${{ matrix.target == 'linux' }}
        run: |
          # scons platform=linuxbsd arch=x86_64 lto=full profile="custom.py" target=template_debug
          scons platform=linuxbsd arch=x86_64 lto=full profile="custom.py" target=template_release debug_symbols=no

          # scons platform=linuxbsd arch=x86_32 lto=full profile="custom.py" target=template_debug
          scons platform=linuxbsd arch=x86_32 lto=full profile="custom.py" target=template_release debug_symbols=no

      - name: Update POSIX
        if: ${{ matrix.target == 'windows' }}
        run: |
          sudo update-alternatives --set x86_64-w64-mingw32-gcc \
            /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ \
            /usr/bin/x86_64-w64-mingw32-g++-posix

          sudo update-alternatives --set i686-w64-mingw32-gcc \
            /usr/bin/i686-w64-mingw32-gcc-posix
          sudo update-alternatives --set i686-w64-mingw32-g++ \
            /usr/bin/i686-w64-mingw32-g++-posix

          echo "MinGW-w64:"
          x86_64-w64-mingw32-gcc --version
          i686-w64-mingw32-gcc --version

      - name: Install Direct3D 12 Driver
        if: ${{ matrix.target == 'windows' }}
        run: |
          python ./misc/scripts/install_d3d12_sdk_windows.py

      - name: Build Windows export template
        if: ${{ matrix.target == 'windows' }}
        run: |
          # scons platform=windows arch=x86_64 lto=full profile="custom.py" use_mingw=yes target=template_debug
          scons platform=windows arch=x86_64 lto=full profile="custom.py" use_mingw=yes target=template_release debug_symbols=no

          # scons platform=windows arch=x86_32 lto=full profile="custom.py" use_mingw=yes target=template_debug
          scons platform=windows arch=x86_32 lto=full profile="custom.py" use_mingw=yes target=template_release debug_symbols=no

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: export-templates-${{ matrix.target }}
          path: |
            bin/*
            !bin/obj/
