name: Build Godot export templates

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    env:
      GODOT_VERSION: 4.6.1-stable

    strategy:
      fail-fast: false
      matrix:
        include:
          # - target: android
          #   arch: arm64
          #   # type: release
          #   runner: ubuntu-24.04

          # # - target: android
          # #   arch: arm64
          # #   # type: debug
          # #   runner: ubuntu-24.04

          - target: android
            arch: arm32-arm64
            # type: release
            runner: ubuntu-24.04

          # - target: android
          #   arch: arm32
          #   # type: release
          #   runner: ubuntu-24.04

          # # - target: android
          # #   arch: arm32
          # #   # type: debug
          # #   runner: ubuntu-24.04

          # # - target: android
          # #   arch: arm32-arm64
          # #   # type: debug
          # #   runner: ubuntu-24.04







          # Linux
          - target: linuxbsd
            arch: x86_64
            # type: release
            runner: ubuntu-22.04

          # - target: linuxbsd
          #   arch: x86_64
          #   type: debug
          #   runner: ubuntu-22.04

          # - target: linuxbsd
          #   arch: arm64
          #   runner: ubuntu-22.04

          # - target: linuxbsd
          #   arch: x86_32
          #   # type: release
          #   runner: ubuntu-22.04

          # - target: linuxbsd
          #   arch: x86_32
          #   type: debug
          #   runner: ubuntu-22.04

          # Windows
          - target: windows
            arch: x86_64
            # type: release
            runner: ubuntu-24.04

          # - target: windows
          #   arch: x86_64
          #   type: debug
          #   runner: ubuntu-24.04

          # - target: windows
          #   arch: arm64
          #   runner: ubuntu-24.04

          # - target: windows
          #   arch: x86_32
          #   # type: release
          #   runner: ubuntu-24.04

          # - target: windows
          #   arch: x86_32
          #   type: debug
          #   runner: ubuntu-24.04

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Build Godot project
        uses: nndda/build-godot@dbb6f41aab715a28894f4c324ffb2ea767b21b2f
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: export-template-${{ matrix.target }}-${{ matrix.arch }}
          path: ${{ matrix.target }}-${{ matrix.arch }}.7z
